# Generated by Django 5.0.1 on 2024-07-01 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_caphsmetrics_haimetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='caphs_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CAPHSMetric', to='core.caphsmetrics'),
        ),
        migrations.AddField(
            model_name='facility',
            name='hai_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HAIMetric', to='core.haimetrics'),
        ),
    ]
