# Generated by Django 5.0.1 on 2024-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facility_caphs_metric_facility_hai_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_id',
            field=models.CharField(default=1231231, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facility',
            name='care_type',
            field=models.CharField(max_length=100),
        ),
    ]
