# Generated by Django 5.0.1 on 2024-07-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facility_facility_id_alter_facility_care_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='caphs_metric',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='hai_metric',
        ),
        migrations.AddField(
            model_name='caphsmetrics',
            name='facility',
            field=models.ForeignKey(default=100000, on_delete=django.db.models.deletion.CASCADE, related_name='caphs_metrics', to='core.facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haimetrics',
            name='facility',
            field=models.ForeignKey(default=110000, on_delete=django.db.models.deletion.CASCADE, related_name='hai_metrics', to='core.facility'),
            preserve_default=False,
        ),
    ]
