# Generated by Django 5.0.6 on 2024-07-09 05:04

import core.models.facility
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_facility_care_type_facility_care_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='care_types',
            field=core.models.facility.ModifiedArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ED', 'ED'), ('Hospital', 'Hospital'), ('Home Health', 'Home Health'), ('Hospice', 'Hospice'), ('Outpatient', 'Outpatient')], max_length=100), size=None), size=None),
        ),
    ]
