# Generated by Django 5.0.6 on 2024-07-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_facility_care_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='haimetrics',
            name='compared_to_national',
            field=models.CharField(default='No Data', max_length=255),
        ),
        migrations.AddField(
            model_name='haimetrics',
            name='measure_id',
            field=models.CharField(default='No Data', max_length=100),
        ),
        migrations.AddField(
            model_name='haimetrics',
            name='measure_name',
            field=models.CharField(default='No Data', max_length=255),
        ),
        migrations.AddField(
            model_name='haimetrics',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
