# Generated by Django 5.0.6 on 2024-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_facility_care_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haimetrics',
            name='hai_metric_json',
            field=models.JSONField(default=list),
        ),
    ]
