# Generated by Django 5.0.6 on 2024-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_haimetrics_compared_to_national_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haimetrics',
            name='score',
            field=models.CharField(default='Not Available', max_length=255),
        ),
    ]
