# Generated by Django 5.0.6 on 2024-07-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_haimetrics_hai_metric_json'),
        ('core', '0011_remove_haimetrics_compared_to_national_and_more'),
    ]

    operations = [
    ]
