# Generated by Django 5.0.1 on 2024-10-21 05:04

import core.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_address_latitude_address_longitude_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDictionaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cms_term', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('source_file', models.URLField(blank=True, null=True)),
                ('care_types', core.models.fields.ModifiedArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ED', 'ED'), ('Hospital', 'Hospital'), ('Home Health', 'Home Health'), ('Hospice', 'Hospice'), ('Outpatient', 'Outpatient')], max_length=100), size=None), size=None)),
                ('definition', models.TextField(blank=True, null=True)),
                ('definition_confidence', models.TextField(blank=True, null=True)),
                ('location_in_website', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
