# Generated by Django 4.0.4 on 2025-02-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_datadictionarymodel_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
